### ISSUE TITLE
Image Resize on Event Handler

### ISSUE THREAD

**Issue by roxdrigoo** [blackcity/Backload#68] opened 2015-12-10 01:27 UTC
After update to the last version (2.1.0) I noticed that height resize was wrong for all images that I upload. I define the size for each request, so I do this by event handler. This method worked fine till I update to the last version.

e.Context.Configuration.Images.Height= height;

If i try to set the value of height bigger than 500(px) the backload automaticaly put 8500(px). There was no way to make it work, so i did the downgrade to the last stable version (2.0.1) and everything returned to work fine.

Probably this is a issue on the method "set" of the property height because the width is ok.

**Comment by blackcity** [comment] 2015-12-10 08:03
Thanks for reporting.

Seems this has something to do with feature request #58. In the 2.1 release a lot of optimizations have been made regarding image processing code. 
I am trying to find out what's the issue and post it here. If there is a problem, it will be fixed soon.

**Comment by blackcity** [comment] 2015-12-10 13:54
I can confirm that this is a bug. It behaves as you described: If you set the height of an image above 500px in code, it war automatically shifted to 8500px within the setter of this property. This is caused by a typo and unfortunately not catched by the modul tests.
We already fixed it internally and we'll upload a minor release in a day or two. Again thanks for your support.

**Comment by Auersberg** [comment] 2015-12-12 13:15
Issue fixed in release 2.1.5 available on Github or NuGet

Download full demo package here:
https://github.com/blackcity/Backload/releases/download/v2.1.5.0/Backload.Standard.2.1.Full.zip

NuGet: 
http://www.nuget.org/packages/backload.Core

**Closed** 2016-01-14 21:48 UTC
Labels: bug
